### ISSUE TITLE
Installing dependencies for Perl?

### ISSUE THREAD

**Issue by SqrtNegInf** [thundergnat/rc-run#1]
I tried to run the Perl (aka Perl 5) task "Dinesman's_multiple-dwelling_problem", but it failed as I didn't have Algorithm::Permute installed.  For Perl 6 you have 'zef' auto-loading dependencies.  What about doing the same for Perl, with 'cpan'?  Or is this just feeping creaturism?

**Comment by thundergnat** [comment]
It is set up to have a "load-dependencies" multi for any language someone cares to write one for. I can probably knock something together for Perl but I have almost no clue about other languages.

**Comment by thundergnat** [comment]
Ok. I have added a perl "load-dependencies" multi. It is heavily Linux oriented and would need to be tweaked for Windows.

**Comment by SqrtNegInf** [comment]
Finally got around to testing this, with the <http://rosettacode.org/wiki/Barnsley_fern#Perl> task, and it had a problem.  Aren't Perl and Perl 6 similar enough in this regard that you could use the same regex pattern from the Perl 6 `check-dependencies` multi?  Tried it that way, and in this case worked.

**Comment by thundergnat** [comment]
Hmm. I'm not sure why I had that as complex as it is. I think I was trying to account for selective feature loading. I had tried it on several entries and it seemed to work so I left it at that. You are probably right about just using the same regex.

**Comment by thundergnat** [comment]
Updated regex. Seems to work ok. Closing for now.
