### ISSUE TITLE
Code extraction failure due to case-sensitive pattern

### ISSUE THREAD

**Issue by SqrtNegInf** [thundergnat/rc-run#2]
It works, have been successfully using it for Perl and Perl 6.  But today I found a problem. 

I was trying to get the Perl entry from <http://rosettacode.org/wiki/Amb>, but it was failing. The fault lies in the regex on line 98, triggered by a non-standard element: some of the language name section markers read 'Header' (initial upper-case) while the regex you use assumes it will be lower-case (as it usually is).   Fix could be as simple as prefacing with `rx:i`

**Comment by thundergnat** [comment]
Argh. I actually went through and fixed all of the non-standard header markup for Perl 6 entries, I'm not taking on fixing all of the other language entries. Your suggestion seems like a reasonable solution.

**Comment by thundergnat** [comment]
Updated regex. A little more forgiving of non-standard markup.
